config/routes.rb
Rails.application.routes.draw do

  resources :tasks
  resources :labels, except: [:index]
  resources :milestones, except: [:index]
  resources :todos, except: [:index, :show]

  root "static_pages#home"

  get '/privacy', to: 'static_pages#privacy'
  get '/legal', to: 'static_pages#terms'
  get '/legal-terms', to: 'static_pages#terms'
  get '/location', to: 'static_pages#location'

  resources :projects, except: [:destroy]
end

app/models/milestone.rb
class Milestone < ApplicationRecord
  validates :label, presence: true
  validates :deadline, presence: true
  
  belongs_to :project

  def active?
    project.open?
  end
end

app/controllers/milestones_controller.rb
class MilestonesController < ApplicationController
  before_action :set_milestone, only: [:show, :edit, :update, :destroy]


  # GET /milestones/1
  def show
  end

  # GET /milestones/new
  def new
    @milestone = Milestone.new
  end

  # GET /milestones/1/edit
  def edit
  end

  # POST /milestones
  def create
    @milestone = Milestone.new(milestone_params)

    if @milestone.save
      redirect_to @milestone.project, notice: 'Milestone was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /milestones/1
  def update
    if @milestone.update(milestone_params)
      redirect_to @milestone.project, notice: 'Milestone was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /milestones/1
  def destroy
    @milestone.destroy
    redirect_to @milestone.project, notice: 'Milestone was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_milestone
      @milestone = Milestone.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def milestone_params
      params.require(:milestone).permit(:label, :deadline, :project_id)
    end
end

app/helpers/milestones_helper.rb
module MilestonesHelper
end

app/views/milestones/_form.html.erb
<%= form_with(model: milestone, local: true) do |form| %>
  <% if milestone.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(milestone.errors.count, "error") %> prohibited this milestone from being saved:</h2>

      <ul>
      <% milestone.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :label %>
    <%= form.text_field :label, id: :milestone_label %>
  </div>

  <div class="field">
    <%= form.label :deadline %>
    <%= form.datetime_select :deadline, id: :milestone_deadline %>
  </div>

  <div class="field">
    <%= form.label :project_id %>

    <%= form.collection_select(:project_id, Project.all.order(:name), :id, :name, id: :todo_project_id )%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/milestones/_milestone.html.erb
<tr>
  <td><%= milestone.label %></td>
  <td><%= milestone.deadline %></td>
  <td><%= link_to 'Show', milestone %></td>
  <td><%= link_to 'Edit', edit_milestone_path(milestone) %></td>
  <td><%= link_to 'Destroy', milestone, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/milestones/edit.html.erb
<h1>Editing Milestone</h1>

<%= render 'form', milestone: @milestone %>

<%= link_to 'Show', @milestone %> |
<%= link_to 'Back', milestones_path %>

app/views/milestones/new.html.erb
<h1>New Milestone</h1>

<%= render 'form', milestone: @milestone %>

<%= link_to 'Back', milestones_path %>

app/views/milestones/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Label:</strong>
  <%= @milestone.label %>
</p>

<p>
  <strong>Deadline:</strong>
  <%= @milestone.deadline %>
</p>

<p>
  <strong>Project:</strong>
  <%= link_to @milestone.project.name, @milestone.project %>
</p>

<p>
  <strong>Active:</strong>
  <%= @milestone.active? %>
</p>

<p>
  <strong>Active second:</strong>
  <%= @milestone.active_second? %>
</p>

<p>
  <strong>Active third:</strong>
  <%= @milestone.active_third? %>
</p>

<%= link_to 'Edit', edit_milestone_path(@milestone) %> |
<%= link_to 'Back', milestones_path %>