config/routes.rb
Rails.application.routes.draw do

  resources :tasks
  resources :labels, except: [:index]
  resources :milestones, except: [:index]
  resources :todos, except: [:index, :show]

  root "static_pages#home"

  get '/privacy', to: 'static_pages#privacy'
  get '/legal', to: 'static_pages#terms'
  get '/legal-terms', to: 'static_pages#terms'
  get '/location', to: 'static_pages#location'

  resources :projects, except: [:destroy]
end

app/models/project.rb
class Project < ApplicationRecord
  validates :name, presence: true
  validates :rating, :inclusion => { :in => 1..5 }, :allow_nil => true

  enum status: [:open, :close] 

  has_many :todos, dependent: :destroy
  has_many :milestones, dependent: :destroy
  has_and_belongs_to_many :labels

  after_initialize :set_defaults
  
  def set_defaults
    if self.new_record?
      self.status ||= :open
    end
  end

  def to_s
    "project #{name}"
  end

  def self.with_todos
    Project.where(id: Todo.all.map(&:project_id))
  end

  def self.total
    Project.all.size
  end

  def self.statuses_for_select
    Project.statuses.map { |key, value| [key.humanize, key] } 
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  def index
    @projects = Project.all
  end

  # GET /projects/1
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  def create
    @project = Project.new(project_params)

    if @project.save
      ProjectMailer.notify_admin(@project).deliver

      redirect_to @project, notice: 'Project was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /projects/1
  def update
    if @project.update(project_params)
      redirect_to @project, notice: 'Project was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /projects/1
  def destroy
    @project.destroy
    redirect_to projects_url, notice: 'Project was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def project_params
      params.require(:project).permit(:name, :rating, :status)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :project_name %>
  </div>

  <div class="field">
    <%= form.label :rating %>
    <%= form.number_field :rating, id: :project_rating %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.select :status, Project.statuses_for_select  %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<tr>
  <td><%= project.name %></td>
  <td><%= project.status %></td>
  <td><%= link_to 'Edit', edit_project_path(project) %></td>
  <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Projects</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Todos</th>
      <th>Labels</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= project.todos.length %></td>
        <td><%= project.labels.length %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @project.rating %>
</p>

<p>
  <strong>Status:</strong>
  <%= @project.status %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

<hr />

<h4>Todos</h4>

<table>
  <thead>
    <tr>
      <th>Label</th>
      <th>Priority</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%= render @project.todos %>
  </tbody>
</table>

<%= link_to 'New Todo', new_todo_path %>

<h4>Milestones</h4>

<table>
  <thead>
    <tr>
      <th>Label</th>
      <th>Deadline</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%= render @project.milestones.order(deadline: :asc) %>
  </tbody>
</table>

<%= link_to 'New Milestone', new_milestone_path %>

<h4>Labels</h4>

<table>
  <thead>
    <tr>
      <th>Label</th>
      <th>color</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%= render @project.labels %>
  </tbody>
</table>

<%= link_to 'New Label', new_label_path %>